version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app-1
    ports:
      - "8080"  
    environment:
      - PORT=8080
    depends_on:
      - mongodb
      - redis
      - zoo
      - redisbloom
    networks:
      - app-network

  app_2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app-2
    ports:
      - "8081"  
    environment:
      - PORT=8081
    depends_on:
      - mongodb
      - redis
      - zoo
      - redisbloom
      - app
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=shortUrl 
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  redisbloom:
    image: redislabs/rebloom:latest
    container_name: redisbloom
    ports:
      - "6379" 
    volumes:
      - redisbloom_data:/data 
    networks:
      - app-network

  zoo:
    image: zookeeper:latest
    container_name: zoo
    ports:
      - "2181"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-loadbalancer
    ports:
      - "80:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
    depends_on:
      - app
      - app_2
    networks:
      - app-network

volumes:
  mongodb_data:
  redis_data:
  redisbloom_data:

networks:
  app-network:
    driver: bridge
